######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 27 02:46:42 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += alarmdialog.h digiclock.h ghari.h mybutton.h
SOURCES += alarmdialog.cpp digiclock.cpp ghari.cpp main.cpp mybutton.cpp
