#############################################################################
# Makefile for building: clock
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Jan 27 02:46:48 2013
# Project:  clock.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile clock.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = alarmdialog.cpp \
		digiclock.cpp \
		ghari.cpp \
		main.cpp \
		mybutton.cpp moc_alarmdialog.cpp \
		moc_digiclock.cpp \
		moc_ghari.cpp \
		moc_mybutton.cpp
OBJECTS       = alarmdialog.o \
		digiclock.o \
		ghari.o \
		main.o \
		mybutton.o \
		moc_alarmdialog.o \
		moc_digiclock.o \
		moc_ghari.o \
		moc_mybutton.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		clock.pro
QMAKE_TARGET  = clock
DESTDIR       = 
TARGET        = clock

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: clock.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile clock.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile clock.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/clock1.0.0 || $(MKDIR) .tmp/clock1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/clock1.0.0/ && $(COPY_FILE) --parents alarmdialog.h digiclock.h ghari.h mybutton.h .tmp/clock1.0.0/ && $(COPY_FILE) --parents alarmdialog.cpp digiclock.cpp ghari.cpp main.cpp mybutton.cpp .tmp/clock1.0.0/ && (cd `dirname .tmp/clock1.0.0` && $(TAR) clock1.0.0.tar clock1.0.0 && $(COMPRESS) clock1.0.0.tar) && $(MOVE) `dirname .tmp/clock1.0.0`/clock1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/clock1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_alarmdialog.cpp moc_digiclock.cpp moc_ghari.cpp moc_mybutton.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_alarmdialog.cpp moc_digiclock.cpp moc_ghari.cpp moc_mybutton.cpp
moc_alarmdialog.cpp: alarmdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) alarmdialog.h -o moc_alarmdialog.cpp

moc_digiclock.cpp: digiclock.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) digiclock.h -o moc_digiclock.cpp

moc_ghari.cpp: ghari.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ghari.h -o moc_ghari.cpp

moc_mybutton.cpp: mybutton.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mybutton.h -o moc_mybutton.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

alarmdialog.o: alarmdialog.cpp mybutton.h \
		alarmdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alarmdialog.o alarmdialog.cpp

digiclock.o: digiclock.cpp digiclock.h \
		mybutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o digiclock.o digiclock.cpp

ghari.o: ghari.cpp digiclock.h \
		mybutton.h \
		ghari.h \
		alarmdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ghari.o ghari.cpp

main.o: main.cpp ghari.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mybutton.o: mybutton.cpp mybutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mybutton.o mybutton.cpp

moc_alarmdialog.o: moc_alarmdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_alarmdialog.o moc_alarmdialog.cpp

moc_digiclock.o: moc_digiclock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_digiclock.o moc_digiclock.cpp

moc_ghari.o: moc_ghari.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ghari.o moc_ghari.cpp

moc_mybutton.o: moc_mybutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mybutton.o moc_mybutton.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

